[package]
name = "sticker-size"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.106"
leptos = { version = "0.8.21", features = ["csr"] }
ril = { version = "0.10", default-features = false, features = ["gif", "png"] }
urlencoding = "2.1.3"
wasm-bindgen = "0.2.129"
web-sys = { version = "0.3", features = ["HtmlInputElement", "FileList", "File", "FileReader"] }
